//
//  AddPortfolioModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 11/3/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddPortfolio
{
    // MARK: Use cases
    
    enum AddPortfolio
    {
        struct Request
        {
            var name: String
            var pairs: [Pair] = []
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
