//
//  AddPortfolioInteractor.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 11/3/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol AddPortfolioBusinessLogic
{
    func addPortfolio(request: AddPortfolio.AddPortfolio.Request)
}

protocol AddPortfolioDataStore
{
    //var name: String { get set }
}

class AddPortfolioInteractor: AddPortfolioBusinessLogic, AddPortfolioDataStore
{
    var presenter: AddPortfolioPresentationLogic?
    var portfolioWorker = PortfolioWorker.sharedInstance
    //var name: String = ""
    
    // MARK: Do something
    
    func addPortfolio(request: AddPortfolio.AddPortfolio.Request) {
        let realm = try! Realm()
        let portfolio = Portfolio()
        portfolio.name = request.name
        try! realm.write {
            
            realm.add(portfolio)
        }
        portfolio.addToWatchlist(pair: realm.object(ofType: Pair.self, forPrimaryKey: "btc-usd-CCCAGG")!)
        
        presenter?.presentAddPortfolio()
    }
}
