//
//  AddPortfolioPresenter.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 11/3/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPortfolioPresentationLogic
{
    func presentAddPortfolio()
}

class AddPortfolioPresenter: AddPortfolioPresentationLogic
{
    weak var viewController: AddPortfolioDisplayLogic?
    
    // MARK: Do something
    
    func presentAddPortfolio() {
        viewController?.dismiss()
    }
}
