//
//  AddTransactionViewController.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol AddTransactionDisplayLogic: class
{
    func dismissCompletedTransaction(viewModel: AddTransaction.SaveTransaction.ViewModel)
    func displayTransaction(viewModel: AddTransaction.LoadTransaction.ViewModel)
}

class AddTransactionViewController: UIViewController, AddTransactionDisplayLogic
{
    var interactor: AddTransactionBusinessLogic?
    var router: (NSObjectProtocol & AddTransactionRoutingLogic & AddTransactionDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = AddTransactionInteractor()
        let presenter = AddTransactionPresenter()
        let router = AddTransactionRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.loadTransaction()
    }
    
    var isBuying: Transaction.OrderType = .Buy
    
    var exchangeNames: [String] = []
    
    var baseNames: [String] = []
    
    var quoteNames: [String] = []
    
    // MARK: Do something
    
    @IBOutlet weak var exchangeSelectionField: UITextField!
    @IBOutlet weak var baseCurrencySelection: UITextField!
    @IBOutlet weak var quoteCurrencySelection: UITextField!
    @IBOutlet weak var currentPriceLabel: UILabel!
    @IBOutlet weak var totalPriceLabel: UILabel!
    @IBOutlet weak var amountField: UITextField!
    @IBOutlet weak var priceField: UITextField!
    
    @IBOutlet weak var buySellIndicator: NSLayoutConstraint!
    
    
    @IBAction func back() {
        self.navigationController?.dismiss(animated: true, completion: nil)
    }
    
    @IBAction func selectBuy() {
        UIView.animate(withDuration: 0.1, animations: {
            self.buySellIndicator.constant = 0
            self.view.layoutIfNeeded()
        }, completion: { (finished) in
            self.isBuying = .Buy
        })
    }
    @IBAction func selectSell() {
        UIView.animate(withDuration: 0.1, animations: {
            self.buySellIndicator.constant = self.view.bounds.width / 2
            self.view.layoutIfNeeded()
        }, completion: { (finished) in
            self.isBuying = .Sell
        })
    }
    
    @IBAction func confirm() {
        let isBuy: Bool = self.isBuying == .Buy
        let req = AddTransaction.SaveTransaction.Request(isBuying: isBuy, amount: Double(amountField.text!)!, price: Double(priceField.text!)!, notes: nil)
        interactor?.saveTransaction(request: req)
    }
    @IBAction func updatePrice() {
        let amountText = self.amountField.text == "" ? "0.0" : self.amountField.text!
        let priceText = self.priceField.text == "" ? "0.0" : self.priceField.text!
        let amount: Double = Double(amountText)!
        let price: Double = Double(priceText)!
        
        let total = amount * price
        self.totalPriceLabel.text = "\(total)"
        
    }
    func loadTransaction() {
        let req = AddTransaction.LoadTransaction.Request()
        interactor?.loadTransaction(request: req)
    }
    func dismissCompletedTransaction(viewModel: AddTransaction.SaveTransaction.ViewModel) {
        
        var vc: UIViewController = self.presentingViewController!
        while((vc.presentingViewController) != nil) {
            vc = vc.presentingViewController!
        }
        vc.dismiss(animated: true, completion: nil)
        
//        self.navigationController?.dismiss(animated: true, completion: nil)
    }
    func displayTransaction(viewModel: AddTransaction.LoadTransaction.ViewModel) {
        self.exchangeNames = viewModel.exchangeNames
        self.quoteNames = viewModel.quoteNames
        
        self.exchangeSelectionField.text = viewModel.exchangeName
        self.baseCurrencySelection.text = viewModel.coinName
        self.quoteCurrencySelection.text = viewModel.quoteName
        
        self.priceField.text = viewModel.currentPrice
        self.currentPriceLabel.text = viewModel.currentPrice
        
        if viewModel.isBuy {
            self.selectBuy()
        } else {
            self.selectSell()
        }
        
        self.updatePrice()
        
        let exchangePicker = UIPickerView()
        exchangePicker.tag = 1
        exchangePicker.delegate = self
        exchangePicker.dataSource = self
        self.exchangeSelectionField.inputView = exchangePicker
        
        let basePicker = UIPickerView()
        basePicker.tag = 2
        basePicker.delegate = self
        basePicker.dataSource = self
        self.baseCurrencySelection.inputView = basePicker
        
        let quotePicker = UIPickerView()
        quotePicker.tag = 2
        quotePicker.delegate = self
        quotePicker.dataSource = self
        self.quoteCurrencySelection.inputView = quotePicker
        
        
//        self.totalPriceLabel.text =
        
    }
    
    
    func loadnewExchange() {
        let req = AddTransaction.LoadTransaction.Request(exchangeName: self.exchangeSelectionField.text, quoteName: self.quoteCurrencySelection.text?.lowercased())
        self.interactor?.loadTransaction(request: req)
    }
    func loadNewPair() {
        let req = AddTransaction.LoadTransaction.Request(exchangeName: self.exchangeSelectionField.text, quoteName: self.quoteCurrencySelection.text?.lowercased())
        self.interactor?.loadTransaction(request: req)
    }
    
    
    
    
}
extension AddTransactionViewController: UIPickerViewDataSource, UIPickerViewDelegate {
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        switch pickerView.tag {
        case 1:
            return exchangeNames.count
        case 2:
            return quoteNames.count
        case 3:
            return quoteNames.count
        default:
            return 0
        }
        
        
    }
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        switch pickerView.tag {
        case 1:
            return exchangeNames[row]
        case 2:
            return quoteNames[row]
        case 3:
            return quoteNames[row]
        default:
            return ""
        }
    }
    func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        
        switch pickerView.tag {
        case 1:
            if exchangeNames.count == 0 {
                return
            }
            self.exchangeSelectionField.text = exchangeNames[row]
            self.loadnewExchange()
        case 2:
            if quoteNames.count == 0 {
                return
            }
            self.quoteCurrencySelection.text = quoteNames[row]
            self.loadNewPair()
        default:
            return
        }
//        self.view.endEditing(true)
    }
}
