//
//  ListTransactionsRouter.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 1/1/18.
//  Copyright (c) 2018 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListTransactionsRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ListTransactionsDataPassing
{
    var dataStore: ListTransactionsDataStore? { get }
}

class ListTransactionsRouter: NSObject, ListTransactionsRoutingLogic, ListTransactionsDataPassing
{
    weak var viewController: ListTransactionsViewController?
    var dataStore: ListTransactionsDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ListTransactionsViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ListTransactionsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
