//
//  ListCoinsModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/23/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListCoins
{
  // MARK: Use cases
  
  
    enum FetchCoins {
        
        struct Request {
            var completion: (Void) -> Void
        }
        struct Response
        {
            struct Coin {
                var symbol: String
                var cap: String
                var price: Double
                var percentage: Double
            }
            var coins: [Coin]
            var gotoTransaction: Bool
            
        }
        struct ViewModel
        {
            struct DisplayableCoin {
                var symbol: String
                var cap: String
                var percentage: String
                var price: String
            }
            
            var coins: [DisplayableCoin]
            var gotoTransaction: Bool
            
        }
    }
    
}
