//
//  ListPortfoliosInteractor.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 10/29/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol ListPortfoliosBusinessLogic
{
    func fetchPortfolios()
}

protocol ListPortfoliosDataStore
{
    var portfolios: Results<Portfolio>! {get set}
}

class ListPortfoliosInteractor: ListPortfoliosBusinessLogic, ListPortfoliosDataStore
{
    var presenter: ListPortfoliosPresentationLogic?
    var worker: ListPortfoliosWorker?
    var portfolios: Results<Portfolio>!
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchPortfolios() {
        let realm = try! Realm()
        let portfolios = realm.objects(Portfolio.self)
        self.portfolios = portfolios
        print(portfolios.count)
        let resp = ListPortfolios.FetchPortfolios.Response(portfolios: portfolios)
        self.presenter?.presentPortfolios(response: resp)
    }
}
