//
//  ListTransactionsModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 1/1/18.
//  Copyright (c) 2018 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListTransactions
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    enum FetchAsset
    {
        struct Request
        {
        }
        struct Response
        {
            var buys: [Transaction]
            var sells: [Transaction]
        }
        struct ViewModel
        {
            struct DisplayableTransaction {
                var pairName: String
                var price: String
                var date: String
                var isBuySide: Bool
                var amount: String
            }
            var transactions: [DisplayableTransaction]
        }
    }
}
