//
//  ListTransactionsInteractor.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 1/1/18.
//  Copyright (c) 2018 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTransactionsBusinessLogic
{
    
    func fetchAsset(request: ListTransactions.FetchAsset.Request)
}

protocol ListTransactionsDataStore
{
    //var name: String { get set }
    var asset: Asset? { get set }
}

class ListTransactionsInteractor: ListTransactionsBusinessLogic, ListTransactionsDataStore
{
    var presenter: ListTransactionsPresentationLogic?
    var worker: ListTransactionsWorker?
    
    var asset: Asset?
    //var name: String = ""
    
    // MARK: Do something
    
    
    
    func fetchAsset(request: ListTransactions.FetchAsset.Request) {
        var a = Array(self.asset!.buys)
        var b = Array(self.asset!.sells)
        var resp = ListTransactions.FetchAsset.Response(buys: a, sells: b)
        presenter?.presentTransactions(response: resp)
    }
}
