//
//  ListTransactionsWorker.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 1/1/18.
//  Copyright (c) 2018 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListTransactionsWorker
{
    func doSomeWork()
    {
    }
}
