//
//  ListCoinsModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/23/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListCoins
{
  // MARK: Use cases
    struct DisplayableCoin {
        var name: String
        var symbol: String
        var cap: String
        var percentage: String
        var price: String
        var isGreen: Bool
    }
  
    enum FetchCoins {
        
        struct Request {
            var completion: (Void) -> Void
        }
        struct Response
        {
            struct Coin {
                var name: String
                var symbol: String
                var cap: String
                var price: Double
                var percentage: Double
            }
            var coins: [Coin]
            var gotoTransaction: Bool
            var doSwitch: Bool = true
            
        }
        struct ViewModel
        {
            
            
            var coins: [DisplayableCoin]
            var gotoTransaction: Bool
            var doSwitch: Bool = true
            
        }
    }
    
    enum SearchCoin {
        struct Request {
            var query: String
        }
        struct Response
        {
            struct Coin {
                var name: String?
                var symbol: String
                var cap: String?
                var price: Double?
                var percentage: Double?
                
                
                
            }
            var coins: [Coin]
//            var gotoTransaction: Bool
//            var doSwitch: Bool = true
            
        }
        struct ViewModel
        {
            
            
            var coins: [DisplayableCoin]
            
            
        }
    }
        
}
