//
//  ListPortfoliosRouter.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 10/29/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListPortfoliosRoutingLogic
{
    func routeToShowPortfolio(segue: UIStoryboardSegue)
}

protocol ListPortfoliosDataPassing
{
    var dataStore: ListPortfoliosDataStore? { get }
}

class ListPortfoliosRouter: NSObject, ListPortfoliosRoutingLogic, ListPortfoliosDataPassing
{
    weak var viewController: ListPortfoliosViewController?
    var dataStore: ListPortfoliosDataStore?
    
    // MARK: Routing
    
    func routeToShowPortfolio(segue: UIStoryboardSegue)
    {
        
        let destinationVC = segue.destination as! ShowPortfolioViewController
        var a = destinationVC.view
        var destinationDS = destinationVC.router!.dataStore!
        print(destinationVC.pieChartView.heroID)
        print(viewController!.portfolioTableView)
        destinationVC.pieChartView.heroID = "pieChart\(viewController!.portfolioTableView.indexPathForSelectedRow!.row)"
        passDataToShowPortfolio(source: dataStore!, destination: &destinationDS)
        
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ListPortfoliosViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    func passDataToShowPortfolio(source: ListPortfoliosDataStore, destination: inout ShowPortfolioDataStore)
    {
        PortfolioWorker.sharedInstance.portfolio = source.portfolios[(viewController?.portfolioTableView.indexPathForSelectedRow?.row)!]
    }
}
