//
//  ListPortfoliosModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 10/29/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum ListPortfolios
{
    // MARK: Use cases
    
    enum FetchPortfolios
    {
        struct Request
        {
        }
        struct Response
        {
            var portfolios: Results<Portfolio>
        }
        struct ViewModel
        {
            struct DisplayablePortfolio {
                var name: String
                var assetNames: [String]
                var assetPercents: [Double]
                var assetValue: String
                var assetChartData: [Double]
                var assetChange: Double
            }
            var portfolios: [DisplayablePortfolio]
            
        }
    }
}
