//
//  SharePortfolioRouter.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 12/27/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SharePortfolioRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SharePortfolioDataPassing
{
  var dataStore: SharePortfolioDataStore? { get }
}

class SharePortfolioRouter: NSObject, SharePortfolioRoutingLogic, SharePortfolioDataPassing
{
  weak var viewController: SharePortfolioViewController?
  var dataStore: SharePortfolioDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SharePortfolioViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SharePortfolioDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
