//
//  ShowPortfolioRouter.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowPortfolioRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowPortfolioDataPassing
{
  var dataStore: ShowPortfolioDataStore? { get }
}

class ShowPortfolioRouter: NSObject, ShowPortfolioRoutingLogic, ShowPortfolioDataPassing
{
  weak var viewController: ShowPortfolioViewController?
  var dataStore: ShowPortfolioDataStore?
  
  // MARK: Routing
    
    func routeToAddTransaction(segue: UIStoryboardSegue) {
        let destinationVC = (segue.destination as! UINavigationController).viewControllers.first! as! ListCoinsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToAddTransaction(source: dataStore!, destination: &destinationDS)
    }
    func passDataToAddTransaction(source: ShowPortfolioDataStore, destination: inout ListCoinsDataStore)
    {
        destination.gotoTransaction = true
    }
    func routeToShowCoin(segue: UIStoryboardSegue) {
        let destinationVC = (segue.destination as! UINavigationController).viewControllers.first! as! ShowCoinViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToShowCoin(source: dataStore!, destination: &destinationDS)
    }
    func passDataToShowCoin(source: ShowPortfolioDataStore, destination: inout ShowCoinDataStore) {
        let coin = PortfolioWorker.sharedInstance.portfolio.assets[viewController!.assetTableView.indexPathForSelectedRow!.row].coin
        destination.coin = MarketWorker.sharedInstance.coinCollection[coin.symbol]
    }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ShowPortfolioViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ShowPortfolioDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
