//
//  ShowCoinModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowCoin
{
    enum Duration {
        case Day
        case Week
        case Month
        case Month3
        case Year
    }
    // MARK: Use cases
    
    enum ShowCoin
    {
        struct Request
        {
            var exchange: String?
            var quote: String?
        }
        struct Response
        {
            var price: Double?
            
            var percent: Double?
            
            var valueChanged: Double?
            
            var volume: Double?
            
            var high24: Double?
            
            var low24: Double?
            
            var name: String
            
            var symbol: String
            
            var quote: String
            
            var exchange: String
            
            var quotes: [String]
            
            var exchanges: [String]
            
            var cap: String
            
            
        }
        struct ViewModel
        {
            var price: String
            
            var open: String
            
            var percent: String
            
            var volume: String
            
            var high24: String
            
            var low24: String
            
            var name: String
            
            var symbol: String
            
            var didIncrease: Bool
            
            var quote: String
            
            var exchange: String
            
            var quotes: [String]
            
            var exchanges: [String]
            
            var cap: String
            
            struct Data {
                var open: Double
                var high: Double
                var low: Double
                var close: Double
                
            }
            var data: Data
            
            
        }
    }
    
    enum FetchChart {
        struct Request {
            var duration: Duration
        }
        struct Response {
            
            var chartData: [(Int, Double, Double, Double, Double, Double)] // unix time, close price, volume
            
            
        }
        struct ViewModel {
            
            var chartData: [(Int, Double, Double, Double, Double, Double)] // unix time, close price, volume
        }
        
    }
    
    enum FetchExchangesAndPair {
        struct Request {
            
        }
        struct Response {
            var exchangeName: String
            var quote: String
            var quotes: [String]
        }
        struct ViewModel {
            var exchangeName: String
            var quote: String
            var quotes: [String]
            
        }
    }
    
    enum FetchFromExchange {
        struct Request {
            var exchangeName: String
            var quote: String
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    enum FetchHoldings {
        struct Request {
            
        }
        struct Response {
            var marketValue: Double
            var initialValue: Double
//            var change24H: Double
            var amount: Double
            var totalGain: Double
            
            var exists: Bool
            var watchlist: Bool
            
        }
        struct ViewModel {
            var marketValue: String
            var initialValue: String
//            var change24H: String
            var amount: String
            var totalGain: String
            
            var exists: Bool
            
            var watchlist: Bool
        }
    }
    
    enum AddToWatchlist {
        struct Request {
            
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }

}
