//
//  ShowPortfolioWorker.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShowPortfolioWorker
{
    let coinWorker = CoinWorker()
    let portfolioWorker = PortfolioWorker.sharedInstance
  
    func fetchAllPrices(completion: @escaping () -> Void) {
        let quotes = ["usd", "btc"]
        let bases: [String] = portfolioWorker.portfolio.assets.filter("coin.coinType != 'fiat'").map { (a) -> String in
            a.coin!.symbol
            } + portfolioWorker.portfolio.watchlist.map({ (c) -> String in
                c.symbol
            })
        let exchange = Exchange()
        exchange.name = "CoinMarketCap"
        coinWorker.fetchMultiple(bases: bases, quotes: quotes, exchange: exchange, completion: completion)
    }
}
