//
//  ShowPortfolioModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowPortfolio
{
  // MARK: Use cases
  
  enum FetchPortfolio
  {
    struct Request
    {
    }
    struct Response
    {
        var value: Double
        
        
        
        var assets: [Asset]
    }
    struct ViewModel
    {
        var totalValue: String
        
        struct DisplayableAsset {
            
            var coinName: String
            
            var amount: String
            
            var totalValue: String
            
            var price: String
            
            var change: String
            
            var isUp: Bool
            
        }
        
        var assets: [DisplayableAsset] = []
    }
  }
    enum FetchAllCoins {
        struct Request {
        
        }
        struct Response {
        
        }
        struct ViewModel {
            
        }
    }
}
