//
//  ShowAccountInteractor.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 9/4/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowAccountBusinessLogic
{
  func doSomething(request: ShowAccount.Something.Request)
}

protocol ShowAccountDataStore
{
  //var name: String { get set }
}

class ShowAccountInteractor: ShowAccountBusinessLogic, ShowAccountDataStore
{
  var presenter: ShowAccountPresentationLogic?
  var worker: ShowAccountWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowAccount.Something.Request)
  {
    worker = ShowAccountWorker()
    worker?.doSomeWork()
    
    let response = ShowAccount.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
