//
//  ShowCoinModels.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowCoin
{
    // MARK: Use cases
    
    enum ShowCoin
    {
        struct Request
        {
            var exchange: String?
            var quote: String?
        }
        struct Response
        {
            var price: Double?
            
            var percent: Double?
            
            var volume: Double?
            
            var name: String
            
            var symbol: String
            
            var quote: String
            
            
            
            
        }
        struct ViewModel
        {
            var price: String
            
            var percent: String
            
            var volume: String
            
            var name: String
            
            var symbol: String
            
            var didIncrease: Bool
            
            var quote: String
            
            
            
            
            
        }
    }
    enum FetchExchangesAndPair {
        struct Request {
            
        }
        struct Response {
            var exchangeName: String
            var quote: String
            var quotes: [String]
        }
        struct ViewModel {
            var exchangeName: String
            var quote: String
            var quotes: [String]
            
        }
    }
    
    enum FetchFromExchange {
        struct Request {
            var exchangeName: String
            var quote: String
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    enum FetchHoldings {
        struct Request {
            
        }
        struct Response {
            var marketValue: Double
            var initialValue: Double
//            var change24H: Double
            var amount: Double
            var totalGain: Double
            
            var exists: Bool
            
        }
        struct ViewModel {
            var marketValue: String
            var initialValue: String
//            var change24H: String
            var amount: String
            var totalGain: String
            
            var exists: Bool
        }
    }

}
