//
//  ShowCoinRouter.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowCoinRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowCoinDataPassing
{
    var dataStore: ShowCoinDataStore? { get }
}

class ShowCoinRouter: NSObject, ShowCoinRoutingLogic, ShowCoinDataPassing
{
    weak var viewController: ShowCoinViewController?
    var dataStore: ShowCoinDataStore?
    
    // MARK: Routing
    
    func routeToAddTransaction(segue: UIStoryboardSegue?) {
//        let destinationVC = segue?.destination as! AddTransactionViewController
        let destinationVC = (segue?.destination as! UINavigationController).viewControllers.first! as! AddTransactionViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToAddTransaction(source: dataStore!, destination: &destinationDS)
    }
    func passDataToAddTransaction(source: ShowCoinDataStore, destination: inout AddTransactionDataStore)
    {
        destination.pair = source.pair
        destination.transactionType = viewController!.transactionType
        destination.coin = source.coin!

        
    }
    func routeToCoinWebsite(segue: UIStoryboardSegue) {
        let destinationVC = segue.destination as! CoinWebsiteViewController
        destinationVC.url = dataStore!.coin!.website
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ShowCoinViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ShowCoinDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
