//
//  ShowPortfolioInteractor.swift
//  CryptoTracker
//
//  Created by Zaizen Kaegyoshi on 8/25/17.
//  Copyright (c) 2017 zaizencorp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPortfolioBusinessLogic
{
    func fetchPortfolio(request: ShowPortfolio.FetchPortfolio.Request)
    func fetchAllCoins()
}

protocol ShowPortfolioDataStore
{
    //var name: String { get set }
}

class ShowPortfolioInteractor: ShowPortfolioBusinessLogic, ShowPortfolioDataStore
{
    var presenter: ShowPortfolioPresentationLogic?
    var portfolioWorker = PortfolioWorker.sharedInstance
    var marketWorker = MarketWorker.sharedInstance
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchPortfolio(request: ShowPortfolio.FetchPortfolio.Request) {
        
        portfolioWorker.updateAssetPrices()
        
        let resp = ShowPortfolio.FetchPortfolio.Response(value: portfolioWorker.portfolio.value, assets: portfolioWorker.portfolio.assets, initialValue: portfolioWorker.portfolio.initialValue)
        presenter?.presentPortfolio(response: resp)
    }
    func fetchAllCoins() {
        self.marketWorker.retrieveCoins(completion: {(d) in })
    }
}
